name: lge-cnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.4.0
  - torchvision=0.5.0
  - cudatoolkit=10.1
  - pytorch-lightning=0.8.5
  - h5py=2.10.0
  - numba=0.48.0
  - matplotlib=3.1.3
  - jupyter=1.0.0
  - tqdm=4.44.1